export type Continent =
  | "Africa"
  | "Asia"
  | "Europe"
  | "North America"
  | "South America"
  | "Oceania";

export const CONTINENTS: Continent[] = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania",
];

const PAVILION_CONTINENT: Record<string, Continent> = {
  AE: "Asia",
  AL: "Europe",
  AM: "Asia",
  AR: "South America",
  AT: "Europe",
  AU: "Oceania",
  AZ: "Asia",
  BA: "Europe",
  BE: "Europe",
  BG: "Europe",
  BR: "South America",
  BS: "North America",
  CA: "North America",
  CD: "Africa",
  CH: "Europe",
  CL: "South America",
  CM: "Africa",
  CN: "Asia",
  CU: "North America",
  CY: "Europe",
  CZSK: "Europe",
  DE: "Europe",
  DK: "Europe",
  EE: "Europe",
  EG: "Africa",
  ES: "Europe",
  ET: "Africa",
  FI: "Europe",
  FR: "Europe",
  GB: "Europe",
  GD: "North America",
  GE: "Asia",
  GN: "Africa",
  GQ: "Africa",
  GR: "Europe",
  GT: "North America",
  HR: "Europe",
  HT: "North America",
  HU: "Europe",
  ID: "Asia",
  IE: "Europe",
  IL: "Asia",
  IN: "Asia",
  IS: "Europe",
  IT: "Europe",
  JP: "Asia",
  KG: "Asia",
  KR: "Asia",
  KZ: "Asia",
  LB: "Asia",
  LT: "Europe",
  LU: "Europe",
  LV: "Europe",
  MA: "Africa",
  MD: "Europe",
  ME: "Europe",
  MK: "Europe",
  MN: "Asia",
  MT: "Europe",
  MX: "North America",
  NL: "Europe",
  NORDIC: "Europe",
  NR: "Oceania",
  NZ: "Oceania",
  OM: "Asia",
  PA: "North America",
  PE: "South America",
  PH: "Asia",
  PK: "Asia",
  PL: "Europe",
  PT: "Europe",
  QA: "Asia",
  RO: "Europe",
  RS: "Europe",
  RU: "Europe",
  SA: "Asia",
  SG: "Asia",
  SI: "Europe",
  SL: "Africa",
  SM: "Europe",
  SN: "Africa",
  SO: "Africa",
  SV: "North America",
  SY: "Asia",
  TL: "Asia",
  TR: "Asia",
  TZ: "Africa",
  UA: "Europe",
  UG: "Africa",
  US: "North America",
  UY: "South America",
  UZ: "Asia",
  VA: "Europe",
  VE: "South America",
  VN: "Asia",
  XK: "Europe",
  ZW: "Africa",
};

export function getContinent(pavilionId: string): Continent | null {
  return PAVILION_CONTINENT[pavilionId] ?? null;
}
